# Generated by Django 3.2.12 on 2022-04-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_signup_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='img',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
