# Generated by Django 3.2.12 on 2022-04-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='img',
            field=models.ImageField(upload_to='doctor/media/'),
        ),
    ]
